import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import Script from "next/script";
import { SERVICE_URLS } from "@sonara/shared";
import { mono, sans, serif } from "@/lib/fonts";
import { publicEnv } from "@/env";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import { SwRegister } from "@/components/sw-register";
import "./globals.css";

// Canonical/OG origin tracks the environment (dev.sonara.fm on the dev build,
// sonara.fm on prod) so link unfurls and canonical URLs are never cross-env.
const ORIGIN = SERVICE_URLS[publicEnv.NEXT_PUBLIC_APP_ENV].web;

export const metadata: Metadata = {
  metadataBase: new URL(ORIGIN),
  title: {
    default: "sonara — music, made visible",
    template: "%s · sonara",
  },
  // og/twitter descriptions are kept in the 110–160 char sweet spot for link
  // unfurls; the <title> default stays short for the browser tab while the
  // social title runs longer.
  description:
    "Sonara turns your music into moving art, right in your browser. Play anything and it paints flowing visuals in time with the sound, as it happens.",
  // og:image / twitter:image come from the file-convention opengraph-image.png
  // + twitter-image.png (the branded 1200×630 card, generated by
  // brand/scripts/build.ts) — don't set images here too.
  openGraph: {
    type: "website",
    title: "sonara — music, made visible: a visualiser that listens",
    description:
      "Sonara turns your music into moving art, right in your browser. Play anything and it paints flowing visuals in time with the sound, as it happens.",
    siteName: "sonara",
    url: ORIGIN,
  },
  twitter: {
    card: "summary_large_image",
    title: "sonara — music, made visible: a visualiser that listens",
    description:
      "Sonara turns your music into moving art, right in your browser. Play anything and it paints flowing visuals in time with the sound, as it happens.",
  },
};

export const viewport: Viewport = {
  themeColor: "#1a1612",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      className={`${serif.variable} ${sans.variable} ${mono.variable}`}
    >
      <head>
        {publicEnv.NEXT_PUBLIC_APP_ENV !== "prod" && (
          <Script
            src="//unpkg.com/react-grab/dist/index.global.js"
            crossOrigin="anonymous"
            strategy="beforeInteractive"
          />
        )}
        {/*
          Cloudflare Web Analytics — privacy-first, cookieless visitor stats.
          The zone has RUM enabled (site_tag below), but CF's edge
          auto-injection doesn't fire for Next's streamed SSR responses, so we
          embed the beacon ourselves. Prod-only: dev traffic stays out of the
          dashboard. View at dash.cloudflare.com → Analytics → Web Analytics.
        */}
        {publicEnv.NEXT_PUBLIC_APP_ENV === "prod" && (
          <Script
            src="https://static.cloudflareinsights.com/beacon.min.js"
            strategy="afterInteractive"
            data-cf-beacon='{"token": "28bb308f1ed44069badd991698616b13"}'
          />
        )}
      </head>
      <body>
        <SwRegister />
        <TooltipProvider delay={100}>
          {children}
          <Toaster
            position="bottom-center"
            theme="dark"
            toastOptions={{
              classNames: {
                toast:
                  "font-mono bg-[color:var(--ink)] text-[color:var(--paper)] border border-[color:var(--hairline)]/40 rounded-none",
                description: "text-[color:var(--stone)]",
                actionButton:
                  "bg-[color:var(--signal)] text-[color:var(--paper)]",
              },
            }}
          />
        </TooltipProvider>
      </body>
    </html>
  );
}
